services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - LOGIN_PASSWORD=${LOGIN_PASSWORD}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - VITE_BACKEND_URL=http://localhost:3001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
