name: Deploy Frontend to Firebase

on:
  push:
    branches: [ "main" ]
    paths:
      - "frontend/**"
      - ".github/workflows/deploy-frontend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        working-directory: frontend
        run: npm ci

      - name: Build with backend URL
        working-directory: frontend
        env:
          VITE_BACKEND_URL: "https://wedding-backend-1039804058960.europe-north2.run.app"
        run: npm run build

      - name: Deploy to Firebase Hosting
        working-directory: frontend
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
